// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNyo9WdevdFyqBAxuqu5szuVejXvvcvt8',
    appId: '1:652131887102:web:be3e13ed643fa597ac82af',
    messagingSenderId: '652131887102',
    projectId: 'lost-found-test-51ce2',
    authDomain: 'lost-found-test-51ce2.firebaseapp.com',
    storageBucket: 'lost-found-test-51ce2.firebasestorage.app',
    measurementId: 'G-16QKYQN05K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzZl9dc4VZK7-s6myY3vWp9JFqcTI9xmc',
    appId: '1:652131887102:android:f1b1a84b1d6bf023ac82af',
    messagingSenderId: '652131887102',
    projectId: 'lost-found-test-51ce2',
    storageBucket: 'lost-found-test-51ce2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABBwNGN7DJwXScYA2C3x6CScndk2ly-0g',
    appId: '1:652131887102:ios:e3775a8b431360f0ac82af',
    messagingSenderId: '652131887102',
    projectId: 'lost-found-test-51ce2',
    storageBucket: 'lost-found-test-51ce2.firebasestorage.app',
    iosBundleId: 'com.example.lostFoundApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABBwNGN7DJwXScYA2C3x6CScndk2ly-0g',
    appId: '1:652131887102:ios:e3775a8b431360f0ac82af',
    messagingSenderId: '652131887102',
    projectId: 'lost-found-test-51ce2',
    storageBucket: 'lost-found-test-51ce2.firebasestorage.app',
    iosBundleId: 'com.example.lostFoundApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNyo9WdevdFyqBAxuqu5szuVejXvvcvt8',
    appId: '1:652131887102:web:16813522f4941f89ac82af',
    messagingSenderId: '652131887102',
    projectId: 'lost-found-test-51ce2',
    authDomain: 'lost-found-test-51ce2.firebaseapp.com',
    storageBucket: 'lost-found-test-51ce2.firebasestorage.app',
    measurementId: 'G-XR6GS03WLC',
  );
}
